# Atividade em Sala

## Pergunta 1

Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo de [0,100] e exiba os valores e o tipo de dado do array.

In [19]:
import numpy as np

# Criação do array
array_numpy = np.random.randint(0, 101, 10)

# Exibição dos valores e tipo de dado
print("Valores do array:", array_numpy)
print("Tipo de dado do array:", array_numpy.dtype)


Valores do array: [52 99 99 21 16 37 38 65 10 43]
Tipo de dado do array: int32


## Pergunta 2

Crie uma matriz de 5x5 com valores aleatórios no intervalo [0,1] e encontre o valor mínimo, máximo e a média da matriz.


In [47]:
import numpy as np

# Criação da matriz
matriz_aleatoria = np.random.rand(5, 5)

# Valor mínimo, máximo e média
valor_minimo = matriz_aleatoria.min()
valor_maximo = matriz_aleatoria.max()
media = matriz_aleatoria.mean()

print("Valor mínimo da matriz:", valor_minimo)
print("Valor máximo da matriz:", valor_maximo)
print("Média da matriz:", media)


Valor mínimo da matriz: 0.01829766884519457
Valor máximo da matriz: 0.9810484854346584
Média da matriz: 0.4447803200889936


## Pergunta 3

Crie um array com 10 elementos aleatórios no intervalo [0,1]. Em seguida, crie um novo array com os 
elementos do primeiro array multiplicados por 10 e convertidos para inteiro.


In [48]:
import numpy as np

# Criação do array original
array_original = np.random.rand(10)

# Cálculo dos elementos multiplicados por 10 e convertidos para inteiro
array_multiplos = (array_original * 10).astype(int)

print("Array original:", array_original)
print("Array com elementos multiplicados por 10:", array_multiplos)


Array original: [0.62958318 0.7941735  0.01406604 0.47771004 0.8714071  0.69955054
 0.09889724 0.15852952 0.7862881  0.08412843]
Array com elementos multiplicados por 10: [6 7 0 4 8 6 0 1 7 0]


## Pergunta 4

Crie um array de duas dimensões com shape (3,3) e valores aleatórios inteiros no intervalo [0,9]. Substitua todos os elementos na segunda linha por -1.


In [64]:
import numpy as np

# Criação do array de duas dimensões
array_2d = np.random.randint(0, 10, (3, 3))

# Substituição dos elementos da segunda linha por -1
array_2d[1, :] = -1

print("Array de duas dimensões:")
print(array_2d)


Array de duas dimensões:
[[ 7  5  8]
 [-1 -1 -1]
 [ 1  1  2]]


## Pergunta 5

Crie um DataFrame com as seguintes informações:

- Coluna "fruta": 'Banana', 'Maçã', 'Pera'
- Coluna "preço": 7.90, 10.20, 11.80
- Coluna "quantidade": 12, 3, 4


In [68]:
import pandas as pd

# Dados para o DataFrame
dados = {
    "fruta": ['Banana', 'Maçã', 'Pera'],
    "preço": [7.90, 10.20, 11.80],
    "quantidade": [12, 3, 4]
}

# Criação do DataFrame
df = pd.DataFrame(dados)

print("DataFrame:")
print(df)


DataFrame:
    fruta  preço  quantidade
0  Banana    7.9          12
1    Maçã   10.2           3
2    Pera   11.8           4
